### ISSUE TITLE
Allow choice of trimmer program

### ISSUE THREAD

**Issue by fgvieira** [snakemake-workflows/dna-seq-varlociraptor#53]
Dear all,

not sure if it is supposed to be feature requests in template, but I think it would quite nice to have the option to choose which trimmer to use. For example:
- cutadapt
- fastp
- pear

As I see it, the config could look something like:
```
trimming:
  activate: false
  tool: cutadapt
  cutadapt:
    # Cutadapt options
    ""
  fastp:
    # Fastp options
    ""
  pear:
    # Pear options
    ""
```
